module.exports = Object.freeze({
  BACKGROUND_COLOR: "#0063B2FF",
  PRIMARY_COLOUR: "#9CC3D5FF",
  SECONDARY_COLOUR: "#9CC3D5FF",
  SECONDARY_TEXT_COLOUR: "#0063B2FF",
  PRIMARY_ACTIVE_COLOR: "#FFF",
  SECONDARY_ACTIVE_COLOR: "#FFF",
});
